In [1]:
import re #regular expresion
import pandas as pd

In [2]:

f = open("chat.txt",'r', encoding="utf-8")
data=f.read()
print(type(data))
print(data)

<class 'str'>
21/09/2020, 21:35 - Messages and calls are end-to-end encrypted. No one outside of this chat, not even WhatsApp, can read or listen to them. Tap to learn more.
06/05/2019, 21:22 - Harsh created group "Karn's ka jalwa 😎😎😎"
21/09/2020, 20:39 - Harsh added you
21/09/2020, 21:41 - Bhartendu Karn😊😊: Thanku  manu🙏🏻
21/09/2020, 21:41 - Harsh: Hiiii papa
21/09/2020, 21:41 - Harsh: 😍😍😍
21/09/2020, 21:41 - Sakshi: Hiii
21/09/2020, 21:42 - Margi: Hiii papa
21/09/2020, 21:42 - Bhartendu Karn😊😊: Ttt
21/09/2020, 21:42 - Harsh: 😲😲😲
21/09/2020, 21:42 - Bhartendu Karn😊😊: Tofobh
21/09/2020, 21:42 - Harsh: ❤️
21/09/2020, 21:42 - Bhartendu Karn😊😊: 😊😊😊
21/09/2020, 21:42 - Harsh: 🙃
21/09/2020, 21:43 - Harsh: Kkrh papa?
21/09/2020, 21:43 - Bhartendu Karn😊😊: Gbg
21/09/2020, 21:44 - Harsh: 🙏🏻
21/09/2020, 21:45 - Margi: Papa meko bhi reply karo na
21/09/2020, 21:47 - Bhartendu Karn😊😊: Chat kar raha hu bata🌝
21/09/2020, 21:48 - Harsh: Ha papa kro 😃😃
21/09/2020, 21:55 - Sakshi: <Media omitted>
23/09/2020, 21:45 - Bhartendu Karn😊😊: Kya  kar rahi hai manu😊
23/09/2020, 21:46 - Sakshi: Bol manu
23/09/2020, 21:46 - Harsh: Phone khel rhi hu papa🤭🤭
23/09/2020, 21:46 - Sakshi: Bus
23/09/2020, 21:47 - Sakshi: Chat kyu nhi aayi
23/09/2020, 21:47 - Margi: Meko bhi pucho na
23/09/2020, 21:47 - Margi: 🥺🥺🥺🥺
23/09/2020, 21:47 - Sakshi: Nhi puchenge
23/09/2020, 21:47 - Harsh: 🤯
23/09/2020, 21:47 - Sakshi: 😤😤
23/09/2020, 21:47 - Sakshi: <Media omitted>
23/09/2020, 21:48 - Margi: <Media omitted>
23/09/2020, 21:50 - Sakshi: <Media omitted>
23/09/2020, 21:51 - Margi: 🤣🤣🤣🤣
23/09/2020, 21:51 - Sakshi: <Media omitted>
23/09/2020, 21:51 - Sakshi: <Media omitted>
23/09/2020, 21:51 - Sakshi: <Media omitted>
23/09/2020, 21:51 - Sakshi: <Media omitted>
23/09/2020, 21:51 - Sakshi: <Media omitted>
23/09/2020, 21:52 - Harsh: <Media omitted>
23/09/2020, 21:54 - Mummi: son a na hi kya
23/09/2020, 21:54 - Harsh: <Media omitted>
23/09/2020, 21:59 - Sakshi: 🥴🥴🥴🥴
21/10/2020, 19:44 - Sakshi: <Media omitted>
21/10/2020, 19:44 - Sakshi: <Media omitted>
21/10/2020, 19:46 - Sakshi: <Media omitted>
21/10/2020, 19:46 - Sakshi: <Media omitted>
21/10/2020, 19:47 - Sakshi: <Media omitted>
21/10/2020, 19:48 - Sakshi: <Media omitted>
21/10/2020, 19:49 - Sakshi: <Media omitted>
21/10/2020, 19:50 - Sakshi: <Media omitted>
21/10/2020, 19:50 - Sakshi: <Media omitted>
22/10/2020, 17:46 - Margi: <Media omitted>
22/10/2020, 18:54 - Margi: <Media omitted>
22/10/2020, 18:54 - Margi: <Media omitted>
15/11/2020, 18:11 - Sakshi: <Media omitted>
15/11/2020, 18:11 - Sakshi: <Media omitted>
15/11/2020, 18:11 - Sakshi: <Media omitted>
15/11/2020, 20:59 - Sakshi: <Media omitted>
20/12/2020, 21:33 - Mummi: <Media omitted>
20/12/2020, 21:54 - Mummi: <Media omitted>
20/12/2020, 21:55 - Mummi: <Media omitted>
20/12/2020, 21:57 - Mummi: <Media omitted>
23/12/2020, 18:26 - Sakshi: <Media omitted>
23/12/2020, 18:26 - Sakshi: <Media omitted>
23/12/2020, 18:26 - Sakshi: <Media omitted>
23/12/2020, 18:26 - Sakshi: <Media omitted>
23/12/2020, 18:27 - Sakshi: <Media omitted>
23/12/2020, 18:27 - Sakshi: <Media omitted>
23/12/2020, 18:27 - Sakshi: <Media omitted>
23/12/2020, 18:27 - Sakshi: <Media omitted>
23/12/2020, 18:27 - Sakshi: <Media omitted>
23/12/2020, 18:27 - Sakshi: <Media omitted>
23/12/2020, 18:27 - Sakshi: <Media omitted>
23/12/2020, 18:27 - Sakshi: <Media omitted>
23/12/2020, 18:27 - Sakshi: <Media omitted>
23/12/2020, 18:27 - Sakshi: <Media omitted>
23/12/2020, 18:27 - Sakshi: <Media omitted>
23/12/2020, 18:27 - Sakshi: <Media omitted>
23/12/2020, 18:27 - Sakshi: <Media omitted>
23/12/2020, 18:27 - Sakshi: <Media omitted>
23/12/2020, 18:27 - Sakshi: <Media omitted>
23/12/2020, 18:27 - Sakshi: <Media omitted>
23/12/2020, 18:29 - Sakshi: <Media omitted>
23/12/2020, 18:29 - Sakshi: <Media omitted>
23/12/2020, 18:29 - Sakshi: <Media omitted>
23/12/2020, 18:29 - Sakshi: <Media omitted>
23/12/2020, 18:29 - Sakshi: <Media omitted>
23/12/2020, 18:29 - Sakshi: <Media omitted>
23/12/2020, 18:29 - Sakshi: <Media omitted>
23/12/2020, 18:29 - Sakshi: <Media omitted>
23/12/2020, 18:29 - Sakshi: <Media omitted>
23/12/2020, 18:29 - Sakshi: <Media omitted>
23/12/2020, 18:29 - Sakshi: <Media omitted>
23/12/2020, 18:29 - Sakshi: <Media omitted>
23/12/2020, 18:29 - Sakshi: <Media omitted>
23/12/2020, 18:29 - Sakshi: <Media omitted>
23/12/2020, 18:29 - Sakshi: <Media omitted>
23/12/2020, 18:29 - Sakshi: <Media omitted>
23/12/2020, 18:29 - Sakshi: <Media omitted>
24/12/2020, 08:33 - Bhartendu Karn😊😊: <Media omitted>
25/12/2020, 09:32 - Harsh: <Media omitted>
25/12/2020, 12:35 - Harsh: <Media omitted>
25/12/2020, 14:11 - Bhartendu Karn😊😊: <Media omitted>
25/12/2020, 14:24 - Sakshi: <Media omitted>
25/12/2020, 14:30 - Harsh: Hii
25/12/2020, 14:30 - Margi: <Media omitted>
25/12/2020, 14:31 - Harsh: @bkarn hi
25/12/2020, 14:31 - Margi: @917647845988
25/12/2020, 14:32 - Margi: @917647845988
26/12/2020, 19:53 - Sakshi: <Media omitted>
26/12/2020, 20:12 - Margi: <Media omitted>
26/12/2020, 20:12 - Harsh: <Media omitted>
26/12/2020, 20:12 - Harsh: <Media omitted>
26/12/2020, 20:16 - Sakshi: <Media omitted>
26/12/2020, 22:03 - Harsh: <Media omitted>
27/12/2020, 13:03 - Margi: <Media omitted>
27/12/2020, 13:03 - Margi: <Media omitted>
27/12/2020, 13:03 - Margi: <Media omitted>
27/12/2020, 13:03 - Margi: <Media omitted>
27/12/2020, 13:03 - Margi: <Media omitted>
27/12/2020, 13:03 - Margi: <Media omitted>
27/12/2020, 13:03 - Margi: <Media omitted>
27/12/2020, 13:03 - Margi: <Media omitted>
27/12/2020, 13:03 - Margi: <Media omitted>
27/12/2020, 13:03 - Margi: <Media omitted>
27/12/2020, 13:03 - Margi: <Media omitted>
27/12/2020, 13:03 - Margi: <Media omitted>
27/12/2020, 13:03 - Margi: <Media omitted>
27/12/2020, 13:03 - Margi: Mummy tang kar rhi meko
27/12/2020, 13:16 - Sakshi: 🤣🤣🤣
27/12/2020, 13:17 - Harsh: Mst mummi😍😘😘😚😚😙😗
27/12/2020, 13:19 - Sakshi: <Media omitted>
27/12/2020, 13:24 - Harsh: <Media omitted>
27/12/2020, 13:25 - Sakshi: <Media omitted>
29/12/2020, 18:05 - Margi: <Media omitted>
29/12/2020, 18:05 - Margi: <Media omitted>
29/12/2020, 18:05 - Margi: <Media omitted>
29/12/2020, 20:15 - Sakshi: *ऑनलाइन क्लास और एक्जाम के लिए कई छात्रों के पास स्मार्टफ़ोन या लैपटॉप जैसी उचित सुविधाएं नहीं हैं। इसलिए सरकार सभी छात्रों को मुफ्त टैबलेट प्रदान कर रही है।*
*ताकि छात्र ऑनलाइन कक्षाओं की मदद से अपनी शिक्षा पूरी कर सकें।*

*आप नीचे दिए गए लिंक से अपना मुफ्त टैबलेट प्राप्त करने के लिए फ़ॉर्म भर सकते हैं।*

👉  http://bit.ly/Registration-Free-Tablets


🙏🙏 *निवेदन*: 🙏 *लोगों की सुविधा के लिए, इस संदेश को जितना संभव हो उतना Share करें ताकि जिन लोगों को मुफ्त टैबलेट की आवश्यकता है, वे उन्हें प्राप्त कर सकें और हमारे देश की साक्षरता दर में सुधार हो सके।*
29/12/2020, 21:58 - Bhartendu Karn😊😊: <Media omitted>
29/12/2020, 22:01 - Bhartendu Karn😊😊: <Media omitted>
30/12/2020, 08:16 - Bhartendu Karn😊😊: <Media omitted>
31/12/2020, 16:56 - Sakshi: <Media omitted>
31/12/2020, 16:56 - Sakshi: <Media omitted>
01/01/2021, 08:04 - Sakshi: <Media omitted>
01/01/2021, 08:17 - Harsh: <Media omitted>
01/01/2021, 09:53 - Harsh: <Media omitted>
01/01/2021, 12:51 - Margi: <Media omitted>
01/01/2021, 12:51 - Margi: <Media omitted>
01/01/2021, 12:52 - Margi: <Media omitted>
01/01/2021, 12:52 - Margi: <Media omitted>
01/01/2021, 12:52 - Margi: <Media omitted>
01/01/2021, 12:52 - Margi: <Media omitted>
01/01/2021, 12:52 - Margi: <Media omitted>
01/01/2021, 12:52 - Margi: <Media omitted>
01/01/2021, 12:52 - Margi: <Media omitted>
01/01/2021, 12:52 - Margi: <Media omitted>
01/01/2021, 12:52 - Margi: <Media omitted>
01/01/2021, 12:52 - Margi: <Media omitted>
01/01/2021, 12:52 - Margi: <Media omitted>
01/01/2021, 12:52 - Margi: <Media omitted>
01/01/2021, 12:52 - Margi: <Media omitted>
01/01/2021, 12:52 - Margi: <Media omitted>
01/01/2021, 12:52 - Margi: <Media omitted>
01/01/2021, 12:52 - Margi: <Media omitted>
01/01/2021, 12:52 - Margi: <Media omitted>
01/01/2021, 12:52 - Margi: <Media omitted>
01/01/2021, 12:52 - Margi: <Media omitted>
01/01/2021, 12:52 - Margi: <Media omitted>
01/01/2021, 12:52 - Margi: <Media omitted>
02/01/2021, 19:59 - Margi: *ठण्ड बहुत बढ़ गईं है, अपने हाथ सेक लो,*
*फिर मत कहना की हमने ध्यान नही रखा आपका*🙏😊
02/01/2021, 19:59 - Margi: <Media omitted>
02/01/2021, 20:00 - Sakshi: Bada bhari Baal to fek nhi saki
02/01/2021, 20:00 - Sakshi: Or dhyaan rakhegi😡
02/01/2021, 20:02 - Sakshi: <Media omitted>
02/01/2021, 21:05 - Harsh: <Media omitted>
02/01/2021, 21:05 - Harsh: <Media omitted>
02/01/2021, 21:05 - Harsh: <Media omitted>
02/01/2021, 21:05 - Harsh: <Media omitted>
04/01/2021, 18:50 - Margi: <Media omitted>
05/01/2021, 18:22 - Sakshi: <Media omitted>
05/01/2021, 18:54 - Margi: <Media omitted>
05/01/2021, 18:58 - Harsh: 😂😂
05/01/2021, 18:59 - Sakshi: 🤣
05/01/2021, 19:06 - Margi: <Media omitted>
05/01/2021, 19:12 - Sakshi: <Media omitted>
05/01/2021, 19:35 - Margi: <Media omitted>
07/01/2021, 18:03 - Harsh: <Media omitted>
07/01/2021, 18:08 - Harsh: Papa
07/01/2021, 18:08 - Harsh: Phone khel rhe ho
07/01/2021, 18:09 - Bhartendu Karn😊😊: Bahut acha laga👌🏻👌🏻
07/01/2021, 18:09 - Harsh: <Media omitted>
07/01/2021, 18:10 - Harsh: <Media omitted>
07/01/2021, 18:35 - Sakshi: Banana front page
07/01/2021, 19:19 - Harsh: 🙆🏻‍♀️🙆🏻‍♀️
07/01/2021, 19:20 - Sakshi: 🤣
07/01/2021, 22:48 - Harsh: <Media omitted>
07/01/2021, 22:51 - Harsh: <Media omitted>
07/01/2021, 22:51 - Harsh: <Media omitted>
08/01/2021, 17:16 - Harsh: <Media omitted>
08/01/2021, 17:16 - Harsh: <Media omitted>
08/01/2021, 17:39 - Margi: 😂😂😂😂😂😂😂
08/01/2021, 17:39 - Harsh: <Media omitted>
08/01/2021, 17:39 - Harsh: <Media omitted>
08/01/2021, 18:52 - Harsh: Papa😂😂
08/01/2021, 18:52 - Harsh: Phone khel rhe ho😂😂
08/01/2021, 18:56 - Harsh: <Media omitted>
08/01/2021, 18:59 - Mummi: Hi
08/01/2021, 18:59 - Sakshi: Yes mummi🤩🤩🤩
08/01/2021, 18:59 - Mummi: Krh
08/01/2021, 19:00 - Harsh: Hii
08/01/2021, 19:00 - Bhartendu Karn😊😊: Ye koi ghomne ki jagah hai kya
08/01/2021, 19:01 - Sakshi: This message was deleted
08/01/2021, 19:01 - Sakshi: <Media omitted>
08/01/2021, 19:01 - Harsh: <Media omitted>
08/01/2021, 19:01 - Mummi: Justice pass karho
08/01/2021, 19:01 - Harsh: <Media omitted>
08/01/2021, 19:02 - Sakshi: <Media omitted>
10/01/2021, 23:50 - Harsh: <Media omitted>
11/01/2021, 12:26 - Sakshi: https://youtu.be/KULXOQCPNf4
12/01/2021, 20:34 - Sakshi: <Media omitted>
12/01/2021, 20:34 - Sakshi: <Media omitted>
12/01/2021, 20:34 - Sakshi: <Media omitted>
12/01/2021, 20:34 - Sakshi: <Media omitted>
12/01/2021, 20:34 - Sakshi: <Media omitted>
12/01/2021, 20:34 - Sakshi: <Media omitted>
12/01/2021, 20:34 - Sakshi: <Media omitted>
12/01/2021, 20:34 - Sakshi: <Media omitted>
12/01/2021, 20:34 - Sakshi: <Media omitted>
12/01/2021, 20:34 - Sakshi: <Media omitted>
12/01/2021, 20:34 - Sakshi: <Media omitted>
12/01/2021, 20:34 - Sakshi: <Media omitted>
12/01/2021, 20:34 - Sakshi: <Media omitted>
12/01/2021, 20:34 - Sakshi: <Media omitted>
12/01/2021, 20:34 - Sakshi: <Media omitted>
12/01/2021, 20:34 - Sakshi: <Media omitted>
12/01/2021, 20:34 - Sakshi: <Media omitted>
12/01/2021, 20:34 - Sakshi: <Media omitted>
12/01/2021, 20:34 - Sakshi: <Media omitted>
12/01/2021, 20:34 - Sakshi: <Media omitted>
12/01/2021, 20:34 - Sakshi: <Media omitted>
12/01/2021, 20:34 - Sakshi: <Media omitted>
12/01/2021, 20:34 - Sakshi: <Media omitted>
12/01/2021, 20:34 - Sakshi: <Media omitted>
12/01/2021, 20:34 - Sakshi: <Media omitted>
12/01/2021, 20:34 - Sakshi: <Media omitted>
12/01/2021, 20:34 - Sakshi: <Media omitted>
12/01/2021, 20:34 - Sakshi: <Media omitted>
12/01/2021, 20:34 - Sakshi: <Media omitted>
12/01/2021, 20:34 - Sakshi: <Media omitted>
14/01/2021, 17:28 - Harsh: Hiii papa🤗
14/01/2021, 17:28 - Harsh: <Media omitted>
16/01/2021, 21:11 - Sakshi: <Media omitted>
16/01/2021, 21:13 - Harsh: This message was deleted
16/01/2021, 21:14 - Harsh: <Media omitted>
16/01/2021, 21:14 - Harsh: <Media omitted>
19/01/2021, 13:10 - Harsh: <Media omitted>
19/01/2021, 13:12 - Sakshi: <Media omitted>
19/01/2021, 13:13 - Sakshi: <Media omitted>
19/01/2021, 13:14 - Harsh: <Media omitted>
19/01/2021, 13:14 - Harsh: <Media omitted>
19/01/2021, 20:12 - Sakshi: <Media omitted>
19/01/2021, 20:12 - Sakshi: <Media omitted>
19/01/2021, 20:12 - Sakshi: <Media omitted>
19/01/2021, 20:12 - Sakshi: <Media omitted>
19/01/2021, 20:12 - Sakshi: <Media omitted>
19/01/2021, 20:12 - Sakshi: <Media omitted>
19/01/2021, 20:12 - Sakshi: <Media omitted>
19/01/2021, 20:12 - Sakshi: <Media omitted>
19/01/2021, 20:12 - Sakshi: <Media omitted>
19/01/2021, 20:12 - Sakshi: <Media omitted>
19/01/2021, 21:41 - Sakshi: <Media omitted>
19/01/2021, 21:42 - Harsh: <Media omitted>
21/01/2021, 18:18 - Sakshi: <Media omitted>
21/01/2021, 18:21 - Harsh: <Media omitted>
21/01/2021, 18:22 - Harsh: <Media omitted>
21/01/2021, 18:56 - Sakshi: <Media omitted>
21/01/2021, 19:14 - Margi: <Media omitted>
21/01/2021, 19:15 - Sakshi: <Media omitted>
21/01/2021, 22:16 - Harsh: <Media omitted>
21/01/2021, 22:16 - Harsh: <Media omitted>
21/01/2021, 22:16 - Harsh: <Media omitted>
21/01/2021, 22:16 - Harsh: <Media omitted>
23/01/2021, 16:30 - Sakshi: क्या आपको पता है कि आप जब भी DP फोटो अपना बदलते हैं whatsapp पर तो वो बदल तो जाता है लेकिन आपके सभी पुराने DP को whatsapp save कर लेता है। नीचे दिए हुए लिंक पर क्लिक कर के आप अपना पहला DP देख सकते हैं
https://goo.gl/vVrCZi
23/01/2021, 16:31 - Harsh: <Media omitted>
25/01/2021, 16:49 - Sakshi: <Media omitted>
25/01/2021, 18:49 - Sakshi: <Media omitted>
25/01/2021, 19:29 - Mummi: Hi
27/01/2021, 18:00 - Sakshi: <Media omitted>
27/01/2021, 18:31 - Bhartendu Karn😊😊: Boliye yeah  sahi javab hai🙏🏻🙏🏻
27/01/2021, 18:32 - Harsh: 😂😂
27/01/2021, 18:32 - Harsh: <Media omitted>
27/01/2021, 18:32 - Sakshi: <Media omitted>
27/01/2021, 18:33 - Harsh: <Media omitted>
27/01/2021, 18:35 - Bhartendu Karn😊😊: Manu acha dance kar rahi hai👌🏻👌🏻
27/01/2021, 18:35 - Harsh: <Media omitted>
27/01/2021, 18:35 - Harsh: 😍😍Thanku papa
27/01/2021, 18:37 - Mummi: Bus asap using located ho
27/01/2021, 18:38 - Mummi: <Media omitted>
27/01/2021, 18:38 - Harsh: <Media omitted>
27/01/2021, 18:38 - Bhartendu Karn😊😊: Auar mari virat kohali👌🏻👌🏻
27/01/2021, 18:39 - Harsh: Kon🤔🤔
27/01/2021, 18:39 - Mummi: <Media omitted>
27/01/2021, 18:39 - Mummi: Mumy
27/01/2021, 18:40 - Mummi: Our janamun
27/01/2021, 18:41 - Mummi: <Media omitted>
27/01/2021, 18:42 - Bhartendu Karn😊😊: Qya doukl kaise penda matka rahi hai👌🏻👌🏻👌🏻👌🏻
27/01/2021, 18:42 - Harsh: 😮😳😲😲😮😮😧😧
27/01/2021, 18:43 - Mummi: Bus ho gaya
27/01/2021, 18:43 - Mummi: <Media omitted>
27/01/2021, 18:43 - Harsh: <Media omitted>
27/01/2021, 18:47 - Bhartendu Karn😊😊: Douki i love  you  jaldi aa raha hou😃😃😃😃
27/01/2021, 18:47 - Harsh: Bs papa control😂😂👍🏻
27/01/2021, 18:50 - Bhartendu Karn😊😊: Cantrol annu cantrol🙏🏻🙏🏻🙏🏻🙏🏻
27/01/2021, 18:50 - Harsh: <Media omitted>
27/01/2021, 19:19 - Sakshi: <Media omitted>
27/01/2021, 19:20 - Harsh: <Media omitted>
27/01/2021, 19:22 - Sakshi: <Media omitted>
27/01/2021, 19:23 - Margi: <Media omitted>
27/01/2021, 19:23 - Sakshi: <Media omitted>
27/01/2021, 20:37 - Sakshi: <Media omitted>
27/01/2021, 21:19 - Bhartendu Karn😊😊: <Media omitted>
28/01/2021, 17:17 - Harsh: <Media omitted>
28/01/2021, 17:18 - Harsh: <Media omitted>
28/01/2021, 19:50 - Mummi: <Media omitted>
28/01/2021, 19:50 - Margi: <Media omitted>
28/01/2021, 19:50 - Harsh: <Media omitted>
28/01/2021, 19:51 - Margi: <Media omitted>
28/01/2021, 20:46 - Harsh: <Media omitted>
29/01/2021, 16:56 - Sakshi: <Media omitted>
29/01/2021, 17:04 - Harsh: <Media omitted>
29/01/2021, 17:04 - Harsh: <Media omitted>
29/01/2021, 17:04 - Harsh: <Media omitted>
29/01/2021, 17:06 - Sakshi: <Media omitted>
29/01/2021, 18:11 - Harsh: Bhabhi
29/01/2021, 18:11 - Harsh: Phone jr rhi h
29/01/2021, 18:11 - Harsh: Ky kru
29/01/2021, 18:40 - Margi: Ho gyi baat
31/01/2021, 11:51 - Sakshi: <Media omitted>
31/01/2021, 11:56 - Harsh: <Media omitted>
31/01/2021, 13:25 - Sakshi: <Media omitted>
31/01/2021, 15:14 - Margi: <Media omitted>
31/01/2021, 15:16 - Harsh: <Media omitted>
31/01/2021, 15:16 - Harsh: <Media omitted>
31/01/2021, 22:21 - Mummi: Kkrh
31/01/2021, 22:21 - Harsh: <Media omitted>
31/01/2021, 22:21 - Mummi: <Media omitted>
31/01/2021, 22:22 - Harsh: <Media omitted>
31/01/2021, 22:22 - Sakshi: <Media omitted>
31/01/2021, 22:22 - Sakshi: <Media omitted>
31/01/2021, 22:22 - Harsh: <Media omitted>
31/01/2021, 22:22 - Harsh: <Media omitted>
31/01/2021, 22:22 - Sakshi: <Media omitted>
31/01/2021, 22:22 - Harsh: <Media omitted>
31/01/2021, 22:22 - Sakshi: <Media omitted>
31/01/2021, 22:23 - Harsh: <Media omitted>
31/01/2021, 22:23 - Harsh: <Media omitted>
31/01/2021, 22:23 - Harsh: <Media omitted>
31/01/2021, 22:24 - Harsh: <Media omitted>
03/02/2021, 22:34 - Sakshi: https://www.tv9hindi.com/career/apply-for-scholarship-scheme-in-bihar-mukhymantri-kanya-utthan-yojana-bihar-515562.html
04/02/2021, 11:47 - Harsh: <Media omitted>
06/02/2021, 13:55 - Harsh: <Media omitted>
10/02/2021, 22:45 - Mummi: पत्नी के हांथो का गर्म गर्म खाना खाने के बाद पति का चेहरा जब संतुष्ट होकर गुलाब की तरह जब खिल जाता है, बस! यही *ROSE DAY*🌹हैं!!!

जब पति-पत्नी एक-दूसरे को जिंदगी भर सुख-दुःख में साथ देने की बात करते हैं, बस! वही *PROPOSE DAY*🧎🏻‍♂️हैं !!!

रस्ते पर किसी अनाथ बच्चे को चॉकलेट खिलाओ और उसके हँसते चेहरे पे ख़ुशी देखो बस! वही
*CHOCOLATE DAY* 🍫 हैं!!!

बच्चों के लिये टेडी क्यूँ खरीदें, बल्कि खुद उनके साथ उनके दोस्त बनकर खेलें बस! वही *TEDDY DAY* 🐼 हैं!!!

माता-पिता और सास-ससुर को कभी वृद्धाश्रम में नहीं जाने देंगे, यह वचन ही *PROMISE DAY*🤝🏻 हैं!!!

परिवार में के सभी सदस्य एक दूसरे के काम को सराहे, और एक दूसरे को गले लगा कर प्रोत्साहित करे बस! वही *HUG DAY* 🤗हैं!!!

छुट्टी के दिन परिवार के साथ हँसते-खेलते दिन बिताए, बस! वही *FAMILY VELANTINE DAY*👨‍👩‍👧‍👦 हैं!!!
12/02/2021, 22:17 - Harsh: <Media omitted>
16/02/2021, 10:08 - Sakshi: <Media omitted>
16/02/2021, 14:03 - Sakshi: <Media omitted>
16/02/2021, 14:03 - Sakshi: <Media omitted>
16/02/2021, 14:03 - Sakshi: <Media omitted>
16/02/2021, 14:03 - Sakshi: <Media omitted>
16/02/2021, 14:03 - Sakshi: <Media omitted>
16/02/2021, 14:03 - Margi: <Media omitted>
16/02/2021, 14:03 - Margi: <Media omitted>
16/02/2021, 21:20 - Harsh: <Media omitted>
16/02/2021, 21:21 - Bhartendu Karn😊😊: <Media omitted>
16/02/2021, 21:23 - Bhartendu Karn😊😊: <Media omitted>
16/02/2021, 23:04 - Harsh: <Media omitted>
17/02/2021, 14:00 - Harsh: <Media omitted>
17/02/2021, 18:54 - Sakshi: <Media omitted>
18/02/2021, 22:27 - Harsh: <Media omitted>
19/02/2021, 09:39 - Harsh: <Media omitted>
19/02/2021, 09:39 - Harsh: <Media omitted>
19/02/2021, 09:40 - Margi: Enjoy 😂😂😂😂
19/02/2021, 09:41 - Margi: Parking ke bhar hi hai kya
19/02/2021, 09:42 - Margi: Ander chl de
19/02/2021, 09:42 - Harsh: Haw
19/02/2021, 09:42 - Harsh: Ab aa gyi parking m
19/02/2021, 09:43 - Margi: Thik thik
19/02/2021, 09:50 - Margi: Aaya koi ki nhi
19/02/2021, 09:53 - Harsh: Mere se
19/02/2021, 09:53 - Harsh: Phle bhi
19/02/2021, 09:53 - Harsh: Thi koi
19/02/2021, 09:53 - Margi: Jaan p hchan wali kya
19/02/2021, 09:54 - Harsh: Ha
19/02/2021, 09:57 - Margi: Chl thik hai
19/02/2021, 10:00 - Harsh: Ok
19/02/2021, 17:32 - Harsh: <Media omitted>
19/02/2021, 17:33 - Harsh: <Media omitted>
19/02/2021, 17:33 - Harsh: <Media omitted>
19/02/2021, 17:36 - Margi: <Media omitted>
20/02/2021, 15:56 - Sakshi: This message was deleted
20/02/2021, 22:49 - Harsh: कैरियर को लेकर एक बात दिमाग मे आयी कि ….. ‘डॉक्टरी’ की पढाई के बाद लोग “डॉक्टर’ ही बनते हैं…लेकिन…….
.
‘इंजीनियरिंग’ की पढाई के बाद आप ‘चपरासी’ से लेकर ‘मुख्यमंत्री’ तक कुछ भी बन सकते हैं…. और हाँ …..’लक’ साथ रहा तो ‘इंजीनियर’….भी।
😉
………………….
कहने का मतलब है …”इंजीनियरिंग” में बहुत ज्यादा “स्कोप” है..!!
✌😊✌
कौन कहता है इंजीनियरिंग करके सिर्फ इंजीनियर बनते हैं ? स्वयम देखिए :

रघुराम राजन – RBI गवर्नर (Electrical Engineer)
केजरीवाल – नेता – मुख्यमंत्री (Mechanical Engineer)
ए.आर रहमान-संगीतकार- (Electronics Engineer)
नागार्जुन-तमिल सूपरस्टार (Bachelor of Engineering)
अखिलेश यादव – CM – Uttar Pradesh (Civil environment engineer)
अनिल कुम्बले – Coach of indian Cricket Team (Mechanical engineer)
अजित जोगी- नेता- मुख्यमंत्री
(Mechanical engineer)

In [3]:
pattern='\d{1,2}/\d{1,2}/\d{2,4},\s\d{1,2}:\d{2}\s-\s'

In [4]:
messages = re.split(pattern, data)[1:]
len(messages)
# messages.del("<Media omitted>\n")

8487

In [5]:
dates = re.findall(pattern, data)
dates

['21/09/2020, 21:35 - ',
 '06/05/2019, 21:22 - ',
 '21/09/2020, 20:39 - ',
 '21/09/2020, 21:41 - ',
 '21/09/2020, 21:41 - ',
 '21/09/2020, 21:41 - ',
 '21/09/2020, 21:41 - ',
 '21/09/2020, 21:42 - ',
 '21/09/2020, 21:42 - ',
 '21/09/2020, 21:42 - ',
 '21/09/2020, 21:42 - ',
 '21/09/2020, 21:42 - ',
 '21/09/2020, 21:42 - ',
 '21/09/2020, 21:42 - ',
 '21/09/2020, 21:43 - ',
 '21/09/2020, 21:43 - ',
 '21/09/2020, 21:44 - ',
 '21/09/2020, 21:45 - ',
 '21/09/2020, 21:47 - ',
 '21/09/2020, 21:48 - ',
 '21/09/2020, 21:55 - ',
 '23/09/2020, 21:45 - ',
 '23/09/2020, 21:46 - ',
 '23/09/2020, 21:46 - ',
 '23/09/2020, 21:46 - ',
 '23/09/2020, 21:47 - ',
 '23/09/2020, 21:47 - ',
 '23/09/2020, 21:47 - ',
 '23/09/2020, 21:47 - ',
 '23/09/2020, 21:47 - ',
 '23/09/2020, 21:47 - ',
 '23/09/2020, 21:47 - ',
 '23/09/2020, 21:48 - ',
 '23/09/2020, 21:50 - ',
 '23/09/2020, 21:51 - ',
 '23/09/2020, 21:51 - ',
 '23/09/2020, 21:51 - ',
 '23/09/2020, 21:51 - ',
 '23/09/2020, 21:51 - ',
 '23/09/2020, 21:51 - ',
 '23/09/2020, 21:52 - ',
 '23/09/2020, 21:54 - ',
 '23/09/2020, 21:54 - ',
 '23/09/2020, 21:59 - ',
 '21/10/2020, 19:44 - ',
 '21/10/2020, 19:44 - ',
 '21/10/2020, 19:46 - ',
 '21/10/2020, 19:46 - ',
 '21/10/2020, 19:47 - ',
 '21/10/2020, 19:48 - ',
 '21/10/2020, 19:49 - ',
 '21/10/2020, 19:50 - ',
 '21/10/2020, 19:50 - ',
 '22/10/2020, 17:46 - ',
 '22/10/2020, 18:54 - ',
 '22/10/2020, 18:54 - ',
 '15/11/2020, 18:11 - ',
 '15/11/2020, 18:11 - ',
 '15/11/2020, 18:11 - ',
 '15/11/2020, 20:59 - ',
 '20/12/2020, 21:33 - ',
 '20/12/2020, 21:54 - ',
 '20/12/2020, 21:55 - ',
 '20/12/2020, 21:57 - ',
 '23/12/2020, 18:26 - ',
 '23/12/2020, 18:26 - ',
 '23/12/2020, 18:26 - ',
 '23/12/2020, 18:26 - ',
 '23/12/2020, 18:27 - ',
 '23/12/2020, 18:27 - ',
 '23/12/2020, 18:27 - ',
 '23/12/2020, 18:27 - ',
 '23/12/2020, 18:27 - ',
 '23/12/2020, 18:27 - ',
 '23/12/2020, 18:27 - ',
 '23/12/2020, 18:27 - ',
 '23/12/2020, 18:27 - ',
 '23/12/2020, 18:27 - ',
 '23/12/2020, 18:27 - ',
 '23/12/2020, 18:27 - ',
 '23/12/2020, 18:27 - ',
 '23/12/2020, 18:27 - ',
 '23/12/2020, 18:27 - ',
 '23/12/2020, 18:27 - ',
 '23/12/2020, 18:29 - ',
 '23/12/2020, 18:29 - ',
 '23/12/2020, 18:29 - ',
 '23/12/2020, 18:29 - ',
 '23/12/2020, 18:29 - ',
 '23/12/2020, 18:29 - ',
 '23/12/2020, 18:29 - ',
 '23/12/2020, 18:29 - ',
 '23/12/2020, 18:29 - ',
 '23/12/2020, 18:29 - ',
 '23/12/2020, 18:29 - ',
 '23/12/2020, 18:29 - ',
 '23/12/2020, 18:29 - ',
 '23/12/2020, 18:29 - ',
 '23/12/2020, 18:29 - ',
 '23/12/2020, 18:29 - ',
 '23/12/2020, 18:29 - ',
 '24/12/2020, 08:33 - ',
 '25/12/2020, 09:32 - ',
 '25/12/2020, 12:35 - ',
 '25/12/2020, 14:11 - ',
 '25/12/2020, 14:24 - ',
 '25/12/2020, 14:30 - ',
 '25/12/2020, 14:30 - ',
 '25/12/2020, 14:31 - ',
 '25/12/2020, 14:31 - ',
 '25/12/2020, 14:32 - ',
 '26/12/2020, 19:53 - ',
 '26/12/2020, 20:12 - ',
 '26/12/2020, 20:12 - ',
 '26/12/2020, 20:12 - ',
 '26/12/2020, 20:16 - ',
 '26/12/2020, 22:03 - ',
 '27/12/2020, 13:03 - ',
 '27/12/2020, 13:03 - ',
 '27/12/2020, 13:03 - ',
 '27/12/2020, 13:03 - ',
 '27/12/2020, 13:03 - ',
 '27/12/2020, 13:03 - ',
 '27/12/2020, 13:03 - ',
 '27/12/2020, 13:03 - ',
 '27/12/2020, 13:03 - ',
 '27/12/2020, 13:03 - ',
 '27/12/2020, 13:03 - ',
 '27/12/2020, 13:03 - ',
 '27/12/2020, 13:03 - ',
 '27/12/2020, 13:03 - ',
 '27/12/2020, 13:16 - ',
 '27/12/2020, 13:17 - ',
 '27/12/2020, 13:19 - ',
 '27/12/2020, 13:24 - ',
 '27/12/2020, 13:25 - ',
 '29/12/2020, 18:05 - ',
 '29/12/2020, 18:05 - ',
 '29/12/2020, 18:05 - ',
 '29/12/2020, 20:15 - ',
 '29/12/2020, 21:58 - ',
 '29/12/2020, 22:01 - ',
 '30/12/2020, 08:16 - ',
 '31/12/2020, 16:56 - ',
 '31/12/2020, 16:56 - ',
 '01/01/2021, 08:04 - ',
 '01/01/2021, 08:17 - ',
 '01/01/2021, 09:53 - ',
 '01/01/2021, 12:51 - ',
 '01/01/2021, 12:51 - ',
 '01/01/2021, 12:52 - ',
 '01/01/2021, 12:52 - ',
 '01/01/2021, 12:52 - ',
 '01/01/2021, 12:52 - ',
 '01/01/2021, 12:52 - ',
 '01/01/2021, 12:52 - ',
 '01/01/2021, 12:52 - ',
 '01/01/2021, 12:52 - ',
 '01/01/2021, 12:52 - ',
 '01/01/2021, 12:52 - ',
 '01/01/2021, 12:52 - ',
 '01/01/2021, 12:52 - ',
 '01/01/2021, 12:52 - ',
 '01/01/2021, 12:52 - ',
 '01/01/2021, 12:52 - ',
 '01/01/2021, 12:52 - ',
 '01/01/2021, 12:52 - ',
 '01/01/2021, 12:52 - ',
 '01/01/2021, 12:52 - ',
 '01/01/2021, 12:52 - ',
 '01/01/2021, 12:52 - ',
 '02/01/2021, 19:59 - ',
 '02/01/2021, 19:59 - ',
 '02/01/2021, 20:00 - ',
 '02/01/2021, 20:00 - ',
 '02/01/2021, 20:02 - ',
 '02/01/2021, 21:05 - ',
 '02/01/2021, 21:05 - ',
 '02/01/2021, 21:05 - ',
 '02/01/2021, 21:05 - ',
 '04/01/2021, 18:50 - ',
 '05/01/2021, 18:22 - ',
 '05/01/2021, 18:54 - ',
 '05/01/2021, 18:58 - ',
 '05/01/2021, 18:59 - ',
 '05/01/2021, 19:06 - ',
 '05/01/2021, 19:12 - ',
 '05/01/2021, 19:35 - ',
 '07/01/2021, 18:03 - ',
 '07/01/2021, 18:08 - ',
 '07/01/2021, 18:08 - ',
 '07/01/2021, 18:09 - ',
 '07/01/2021, 18:09 - ',
 '07/01/2021, 18:10 - ',
 '07/01/2021, 18:35 - ',
 '07/01/2021, 19:19 - ',
 '07/01/2021, 19:20 - ',
 '07/01/2021, 22:48 - ',
 '07/01/2021, 22:51 - ',
 '07/01/2021, 22:51 - ',
 '08/01/2021, 17:16 - ',
 '08/01/2021, 17:16 - ',
 '08/01/2021, 17:39 - ',
 '08/01/2021, 17:39 - ',
 '08/01/2021, 17:39 - ',
 '08/01/2021, 18:52 - ',
 '08/01/2021, 18:52 - ',
 '08/01/2021, 18:56 - ',
 '08/01/2021, 18:59 - ',
 '08/01/2021, 18:59 - ',
 '08/01/2021, 18:59 - ',
 '08/01/2021, 19:00 - ',
 '08/01/2021, 19:00 - ',
 '08/01/2021, 19:01 - ',
 '08/01/2021, 19:01 - ',
 '08/01/2021, 19:01 - ',
 '08/01/2021, 19:01 - ',
 '08/01/2021, 19:01 - ',
 '08/01/2021, 19:02 - ',
 '10/01/2021, 23:50 - ',
 '11/01/2021, 12:26 - ',
 '12/01/2021, 20:34 - ',
 '12/01/2021, 20:34 - ',
 '12/01/2021, 20:34 - ',
 '12/01/2021, 20:34 - ',
 '12/01/2021, 20:34 - ',
 '12/01/2021, 20:34 - ',
 '12/01/2021, 20:34 - ',
 '12/01/2021, 20:34 - ',
 '12/01/2021, 20:34 - ',
 '12/01/2021, 20:34 - ',
 '12/01/2021, 20:34 - ',
 '12/01/2021, 20:34 - ',
 '12/01/2021, 20:34 - ',
 '12/01/2021, 20:34 - ',
 '12/01/2021, 20:34 - ',
 '12/01/2021, 20:34 - ',
 '12/01/2021, 20:34 - ',
 '12/01/2021, 20:34 - ',
 '12/01/2021, 20:34 - ',
 '12/01/2021, 20:34 - ',
 '12/01/2021, 20:34 - ',
 '12/01/2021, 20:34 - ',
 '12/01/2021, 20:34 - ',
 '12/01/2021, 20:34 - ',
 '12/01/2021, 20:34 - ',
 '12/01/2021, 20:34 - ',
 '12/01/2021, 20:34 - ',
 '12/01/2021, 20:34 - ',
 '12/01/2021, 20:34 - ',
 '12/01/2021, 20:34 - ',
 '14/01/2021, 17:28 - ',
 '14/01/2021, 17:28 - ',
 '16/01/2021, 21:11 - ',
 '16/01/2021, 21:13 - ',
 '16/01/2021, 21:14 - ',
 '16/01/2021, 21:14 - ',
 '19/01/2021, 13:10 - ',
 '19/01/2021, 13:12 - ',
 '19/01/2021, 13:13 - ',
 '19/01/2021, 13:14 - ',
 '19/01/2021, 13:14 - ',
 '19/01/2021, 20:12 - ',
 '19/01/2021, 20:12 - ',
 '19/01/2021, 20:12 - ',
 '19/01/2021, 20:12 - ',
 '19/01/2021, 20:12 - ',
 '19/01/2021, 20:12 - ',
 '19/01/2021, 20:12 - ',
 '19/01/2021, 20:12 - ',
 '19/01/2021, 20:12 - ',
 '19/01/2021, 20:12 - ',
 '19/01/2021, 21:41 - ',
 '19/01/2021, 21:42 - ',
 '21/01/2021, 18:18 - ',
 '21/01/2021, 18:21 - ',
 '21/01/2021, 18:22 - ',
 '21/01/2021, 18:56 - ',
 '21/01/2021, 19:14 - ',
 '21/01/2021, 19:15 - ',
 '21/01/2021, 22:16 - ',
 '21/01/2021, 22:16 - ',
 '21/01/2021, 22:16 - ',
 '21/01/2021, 22:16 - ',
 '23/01/2021, 16:30 - ',
 '23/01/2021, 16:31 - ',
 '25/01/2021, 16:49 - ',
 '25/01/2021, 18:49 - ',
 '25/01/2021, 19:29 - ',
 '27/01/2021, 18:00 - ',
 '27/01/2021, 18:31 - ',
 '27/01/2021, 18:32 - ',
 '27/01/2021, 18:32 - ',
 '27/01/2021, 18:32 - ',
 '27/01/2021, 18:33 - ',
 '27/01/2021, 18:35 - ',
 '27/01/2021, 18:35 - ',
 '27/01/2021, 18:35 - ',
 '27/01/2021, 18:37 - ',
 '27/01/2021, 18:38 - ',
 '27/01/2021, 18:38 - ',
 '27/01/2021, 18:38 - ',
 '27/01/2021, 18:39 - ',
 '27/01/2021, 18:39 - ',
 '27/01/2021, 18:39 - ',
 '27/01/2021, 18:40 - ',
 '27/01/2021, 18:41 - ',
 '27/01/2021, 18:42 - ',
 '27/01/2021, 18:42 - ',
 '27/01/2021, 18:43 - ',
 '27/01/2021, 18:43 - ',
 '27/01/2021, 18:43 - ',
 '27/01/2021, 18:47 - ',
 '27/01/2021, 18:47 - ',
 '27/01/2021, 18:50 - ',
 '27/01/2021, 18:50 - ',
 '27/01/2021, 19:19 - ',
 '27/01/2021, 19:20 - ',
 '27/01/2021, 19:22 - ',
 '27/01/2021, 19:23 - ',
 '27/01/2021, 19:23 - ',
 '27/01/2021, 20:37 - ',
 '27/01/2021, 21:19 - ',
 '28/01/2021, 17:17 - ',
 '28/01/2021, 17:18 - ',
 '28/01/2021, 19:50 - ',
 '28/01/2021, 19:50 - ',
 '28/01/2021, 19:50 - ',
 '28/01/2021, 19:51 - ',
 '28/01/2021, 20:46 - ',
 '29/01/2021, 16:56 - ',
 '29/01/2021, 17:04 - ',
 '29/01/2021, 17:04 - ',
 '29/01/2021, 17:04 - ',
 '29/01/2021, 17:06 - ',
 '29/01/2021, 18:11 - ',
 '29/01/2021, 18:11 - ',
 '29/01/2021, 18:11 - ',
 '29/01/2021, 18:40 - ',
 '31/01/2021, 11:51 - ',
 '31/01/2021, 11:56 - ',
 '31/01/2021, 13:25 - ',
 '31/01/2021, 15:14 - ',
 '31/01/2021, 15:16 - ',
 '31/01/2021, 15:16 - ',
 '31/01/2021, 22:21 - ',
 '31/01/2021, 22:21 - ',
 '31/01/2021, 22:21 - ',
 '31/01/2021, 22:22 - ',
 '31/01/2021, 22:22 - ',
 '31/01/2021, 22:22 - ',
 '31/01/2021, 22:22 - ',
 '31/01/2021, 22:22 - ',
 '31/01/2021, 22:22 - ',
 '31/01/2021, 22:22 - ',
 '31/01/2021, 22:22 - ',
 '31/01/2021, 22:23 - ',
 '31/01/2021, 22:23 - ',
 '31/01/2021, 22:23 - ',
 '31/01/2021, 22:24 - ',
 '03/02/2021, 22:34 - ',
 '04/02/2021, 11:47 - ',
 '06/02/2021, 13:55 - ',
 '10/02/2021, 22:45 - ',
 '12/02/2021, 22:17 - ',
 '16/02/2021, 10:08 - ',
 '16/02/2021, 14:03 - ',
 '16/02/2021, 14:03 - ',
 '16/02/2021, 14:03 - ',
 '16/02/2021, 14:03 - ',
 '16/02/2021, 14:03 - ',
 '16/02/2021, 14:03 - ',
 '16/02/2021, 14:03 - ',
 '16/02/2021, 21:20 - ',
 '16/02/2021, 21:21 - ',
 '16/02/2021, 21:23 - ',
 '16/02/2021, 23:04 - ',
 '17/02/2021, 14:00 - ',
 '17/02/2021, 18:54 - ',
 '18/02/2021, 22:27 - ',
 '19/02/2021, 09:39 - ',
 '19/02/2021, 09:39 - ',
 '19/02/2021, 09:40 - ',
 '19/02/2021, 09:41 - ',
 '19/02/2021, 09:42 - ',
 '19/02/2021, 09:42 - ',
 '19/02/2021, 09:42 - ',
 '19/02/2021, 09:43 - ',
 '19/02/2021, 09:50 - ',
 '19/02/2021, 09:53 - ',
 '19/02/2021, 09:53 - ',
 '19/02/2021, 09:53 - ',
 '19/02/2021, 09:53 - ',
 '19/02/2021, 09:54 - ',
 '19/02/2021, 09:57 - ',
 '19/02/2021, 10:00 - ',
 '19/02/2021, 17:32 - ',
 '19/02/2021, 17:33 - ',
 '19/02/2021, 17:33 - ',
 '19/02/2021, 17:36 - ',
 '20/02/2021, 15:56 - ',
 '20/02/2021, 22:49 - ',
 '21/02/2021, 13:41 - ',
 '21/02/2021, 13:34 - ',
 '21/02/2021, 17:41 - ',
 '21/02/2021, 20:14 - ',
 '21/02/2021, 20:25 - ',
 '21/02/2021, 21:36 - ',
 '21/02/2021, 21:44 - ',
 '21/02/2021, 21:53 - ',
 '21/02/2021, 21:53 - ',
 '21/02/2021, 21:55 - ',
 '21/02/2021, 22:11 - ',
 '21/02/2021, 22:13 - ',
 '22/02/2021, 19:59 - ',
 '22/02/2021, 21:15 - ',
 '22/02/2021, 21:16 - ',
 '22/02/2021, 21:26 - ',
 '23/02/2021, 18:35 - ',
 '23/02/2021, 21:55 - ',
 '23/02/2021, 21:55 - ',
 '26/02/2021, 18:14 - ',
 '26/02/2021, 19:42 - ',
 '27/02/2021, 20:16 - ',
 '03/03/2021, 21:53 - ',
 '03/03/2021, 21:53 - ',
 '03/03/2021, 21:55 - ',
 '04/03/2021, 17:37 - ',
 '09/03/2021, 09:24 - ',
 '09/03/2021, 21:50 - ',
 '09/03/2021, 22:19 - ',
 '09/03/2021, 22:25 - ',
 '09/03/2021, 22:25 - ',
 '10/03/2021, 13:14 - ',
 '10/03/2021, 13:15 - ',
 '10/03/2021, 13:41 - ',
 '10/03/2021, 14:41 - ',
 '10/03/2021, 20:46 - ',
 '10/03/2021, 21:33 - ',
 '14/03/2021, 13:22 - ',
 '14/03/2021, 13:22 - ',
 '18/03/2021, 20:31 - ',
 '18/03/2021, 20:31 - ',
 '19/03/2021, 15:35 - ',
 '19/03/2021, 16:14 - ',
 '19/03/2021, 16:15 - ',
 '20/03/2021, 22:04 - ',
 '20/03/2021, 22:11 - ',
 '20/03/2021, 22:29 - ',
 '20/03/2021, 22:29 - ',
 '20/03/2021, 22:32 - ',
 '20/03/2021, 22:35 - ',
 '20/03/2021, 22:40 - ',
 '20/03/2021, 22:43 - ',
 '21/03/2021, 13:29 - ',
 '26/03/2021, 18:36 - ',
 '26/03/2021, 18:41 - ',
 '26/03/2021, 18:41 - ',
 '26/03/2021, 18:42 - ',
 '27/03/2021, 22:20 - ',
 '27/03/2021, 22:20 - ',
 '27/03/2021, 22:29 - ',
 '27/03/2021, 22:29 - ',
 '27/03/2021, 22:31 - ',
 '27/03/2021, 22:38 - ',
 '28/03/2021, 13:09 - ',
 '28/03/2021, 13:49 - ',
 '28/03/2021, 13:49 - ',
 '28/03/2021, 13:49 - ',
 '28/03/2021, 13:51 - ',
 '28/03/2021, 13:54 - ',
 '28/03/2021, 13:54 - ',
 '28/03/2021, 13:55 - ',
 '28/03/2021, 13:55 - ',
 '28/03/2021, 13:55 - ',
 '28/03/2021, 13:56 - ',
 '28/03/2021, 13:56 - ',
 '28/03/2021, 14:00 - ',
 '28/03/2021, 14:01 - ',
 '28/03/2021, 15:51 - ',
 '28/03/2021, 18:25 - ',
 '28/03/2021, 18:26 - ',
 '28/03/2021, 18:26 - ',
 '28/03/2021, 18:26 - ',
 '29/03/2021, 11:49 - ',
 '29/03/2021, 11:57 - ',
 '29/03/2021, 12:16 - ',
 '29/03/2021, 12:16 - ',
 '29/03/2021, 12:52 - ',
 '29/03/2021, 13:40 - ',
 '29/03/2021, 13:40 - ',
 '29/03/2021, 13:41 - ',
 '29/03/2021, 13:41 - ',
 '29/03/2021, 13:41 - ',
 '29/03/2021, 13:41 - ',
 '29/03/2021, 13:41 - ',
 '29/03/2021, 13:41 - ',
 '29/03/2021, 13:41 - ',
 '29/03/2021, 13:59 - ',
 '29/03/2021, 19:58 - ',
 '29/03/2021, 20:00 - ',
 '01/04/2021, 15:34 - ',
 '01/04/2021, 18:24 - ',
 '01/04/2021, 18:46 - ',
 '01/04/2021, 19:00 - ',
 '02/04/2021, 16:38 - ',
 '02/04/2021, 16:55 - ',
 '03/04/2021, 16:08 - ',
 '03/04/2021, 17:47 - ',
 '05/04/2021, 20:43 - ',
 '05/04/2021, 21:10 - ',
 '05/04/2021, 21:26 - ',
 '05/04/2021, 21:30 - ',
 '05/04/2021, 21:30 - ',
 '08/04/2021, 23:09 - ',
 '08/04/2021, 23:09 - ',
 '08/04/2021, 23:09 - ',
 '08/04/2021, 23:09 - ',
 '08/04/2021, 23:09 - ',
 '08/04/2021, 23:09 - ',
 '08/04/2021, 23:10 - ',
 '08/04/2021, 23:13 - ',
 '08/04/2021, 23:14 - ',
 '08/04/2021, 23:14 - ',
 '08/04/2021, 23:14 - ',
 '08/04/2021, 23:14 - ',
 '08/04/2021, 23:14 - ',
 '08/04/2021, 23:14 - ',
 '08/04/2021, 23:14 - ',
 '08/04/2021, 23:14 - ',
 '08/04/2021, 23:14 - ',
 '08/04/2021, 23:14 - ',
 '08/04/2021, 23:14 - ',
 '08/04/2021, 23:18 - ',
 '08/04/2021, 23:18 - ',
 '08/04/2021, 23:19 - ',
 '08/04/2021, 23:19 - ',
 '08/04/2021, 23:20 - ',
 '08/04/2021, 23:23 - ',
 '08/04/2021, 23:23 - ',
 '08/04/2021, 23:24 - ',
 '08/04/2021, 23:25 - ',
 '09/04/2021, 20:29 - ',
 '10/04/2021, 13:02 - ',
 '10/04/2021, 20:30 - ',
 '10/04/2021, 20:30 - ',
 '11/04/2021, 12:32 - ',
 '11/04/2021, 16:18 - ',
 '11/04/2021, 16:19 - ',
 '11/04/2021, 16:19 - ',
 '11/04/2021, 16:19 - ',
 '11/04/2021, 16:21 - ',
 '11/04/2021, 16:21 - ',
 '11/04/2021, 17:23 - ',
 '11/04/2021, 17:25 - ',
 '11/04/2021, 17:27 - ',
 '11/04/2021, 17:27 - ',
 '11/04/2021, 21:45 - ',
 '12/04/2021, 13:09 - ',
 '12/04/2021, 15:00 - ',
 '12/04/2021, 22:01 - ',
 '12/04/2021, 22:11 - ',
 '12/04/2021, 22:11 - ',
 '12/04/2021, 22:54 - ',
 '13/04/2021, 12:42 - ',
 '13/04/2021, 14:18 - ',
 '13/04/2021, 18:10 - ',
 '13/04/2021, 18:10 - ',
 '13/04/2021, 18:26 - ',
 '13/04/2021, 18:26 - ',
 '13/04/2021, 18:26 - ',
 '13/04/2021, 19:03 - ',
 '14/04/2021, 22:56 - ',
 '14/04/2021, 22:56 - ',
 '14/04/2021, 22:56 - ',
 '14/04/2021, 22:57 - ',
 '14/04/2021, 22:57 - ',
 '15/04/2021, 08:02 - ',
 '15/04/2021, 08:50 - ',
 '15/04/2021, 08:50 - ',
 '15/04/2021, 09:06 - ',
 '15/04/2021, 10:39 - ',
 '15/04/2021, 11:25 - ',
 '15/04/2021, 16:38 - ',
 '15/04/2021, 16:44 - ',
 '15/04/2021, 16:46 - ',
 '15/04/2021, 16:46 - ',
 '15/04/2021, 16:49 - ',
 '15/04/2021, 19:55 - ',
 '15/04/2021, 19:55 - ',
 '15/04/2021, 19:57 - ',
 '15/04/2021, 19:59 - ',
 '15/04/2021, 20:09 - ',
 '15/04/2021, 20:15 - ',
 '15/04/2021, 22:07 - ',
 '15/04/2021, 22:18 - ',
 '15/04/2021, 22:29 - ',
 '15/04/2021, 22:30 - ',
 '16/04/2021, 08:05 - ',
 '16/04/2021, 17:34 - ',
 '17/04/2021, 15:15 - ',
 '17/04/2021, 16:04 - ',
 '18/04/2021, 11:36 - ',
 '18/04/2021, 11:37 - ',
 '18/04/2021, 12:21 - ',
 '18/04/2021, 13:08 - ',
 '18/04/2021, 13:34 - ',
 '18/04/2021, 13:34 - ',
 '18/04/2021, 13:35 - ',
 '18/04/2021, 13:35 - ',
 '18/04/2021, 13:35 - ',
 '18/04/2021, 13:35 - ',
 '18/04/2021, 13:36 - ',
 '18/04/2021, 13:36 - ',
 '18/04/2021, 13:36 - ',
 '18/04/2021, 13:36 - ',
 '18/04/2021, 16:53 - ',
 '19/04/2021, 11:45 - ',
 '19/04/2021, 17:14 - ',
 '19/04/2021, 17:22 - ',
 '19/04/2021, 17:26 - ',
 '19/04/2021, 17:27 - ',
 '19/04/2021, 17:27 - ',
 '19/04/2021, 17:31 - ',
 '19/04/2021, 17:31 - ',
 '19/04/2021, 17:54 - ',
 '19/04/2021, 17:57 - ',
 '19/04/2021, 18:13 - ',
 '19/04/2021, 18:17 - ',
 '19/04/2021, 18:18 - ',
 '19/04/2021, 18:21 - ',
 '19/04/2021, 18:21 - ',
 '19/04/2021, 18:22 - ',
 '19/04/2021, 19:40 - ',
 '19/04/2021, 19:41 - ',
 '19/04/2021, 19:41 - ',
 '19/04/2021, 19:42 - ',
 '19/04/2021, 19:42 - ',
 '19/04/2021, 19:43 - ',
 '19/04/2021, 20:00 - ',
 '19/04/2021, 20:00 - ',
 '20/04/2021, 13:26 - ',
 '20/04/2021, 13:35 - ',
 '20/04/2021, 13:39 - ',
 '20/04/2021, 15:07 - ',
 '20/04/2021, 15:31 - ',
 '21/04/2021, 09:40 - ',
 '21/04/2021, 11:12 - ',
 '21/04/2021, 11:19 - ',
 '21/04/2021, 11:22 - ',
 '21/04/2021, 11:35 - ',
 '21/04/2021, 12:52 - ',
 '21/04/2021, 12:52 - ',
 '21/04/2021, 12:52 - ',
 '21/04/2021, 12:52 - ',
 '21/04/2021, 13:01 - ',
 '21/04/2021, 13:04 - ',
 '21/04/2021, 13:44 - ',
 '21/04/2021, 13:45 - ',
 '21/04/2021, 15:52 - ',
 '22/04/2021, 12:53 - ',
 '22/04/2021, 13:23 - ',
 '22/04/2021, 13:23 - ',
 '22/04/2021, 13:23 - ',
 '22/04/2021, 13:49 - ',
 '22/04/2021, 13:49 - ',
 '22/04/2021, 17:46 - ',
 '22/04/2021, 22:21 - ',
 '22/04/2021, 22:22 - ',
 '22/04/2021, 22:22 - ',
 '22/04/2021, 22:22 - ',
 '22/04/2021, 22:22 - ',
 '23/04/2021, 21:57 - ',
 '23/04/2021, 22:11 - ',
 '24/04/2021, 11:49 - ',
 '24/04/2021, 12:05 - ',
 '24/04/2021, 16:01 - ',
 '24/04/2021, 18:04 - ',
 '25/04/2021, 10:43 - ',
 '25/04/2021, 13:08 - ',
 '25/04/2021, 22:18 - ',
 '25/04/2021, 22:18 - ',
 '25/04/2021, 22:19 - ',
 '26/04/2021, 12:08 - ',
 '26/04/2021, 12:08 - ',
 '29/04/2021, 15:50 - ',
 '29/04/2021, 15:52 - ',
 '29/04/2021, 15:53 - ',
 '01/05/2021, 22:25 - ',
 '01/05/2021, 22:32 - ',
 '01/05/2021, 22:32 - ',
 '01/05/2021, 22:45 - ',
 '02/05/2021, 09:38 - ',
 '02/05/2021, 10:21 - ',
 '02/05/2021, 11:27 - ',
 '02/05/2021, 18:33 - ',
 '02/05/2021, 18:40 - ',
 '02/05/2021, 18:42 - ',
 '02/05/2021, 18:51 - ',
 '02/05/2021, 18:56 - ',
 '02/05/2021, 18:58 - ',
 '02/05/2021, 22:41 - ',
 '02/05/2021, 22:45 - ',
 '02/05/2021, 22:45 - ',
 '03/05/2021, 11:51 - ',
 '03/05/2021, 16:46 - ',
 '03/05/2021, 17:10 - ',
 '03/05/2021, 19:34 - ',
 '04/05/2021, 08:55 - ',
 '04/05/2021, 10:15 - ',
 '04/05/2021, 12:37 - ',
 '04/05/2021, 17:11 - ',
 '04/05/2021, 22:33 - ',
 '05/05/2021, 15:19 - ',
 '06/05/2021, 20:01 - ',
 '06/05/2021, 20:05 - ',
 '07/05/2021, 09:51 - ',
 '07/05/2021, 11:56 - ',
 '07/05/2021, 18:39 - ',
 '07/05/2021, 18:39 - ',
 '07/05/2021, 20:06 - ',
 '07/05/2021, 20:06 - ',
 '07/05/2021, 20:06 - ',
 '07/05/2021, 20:12 - ',
 '07/05/2021, 20:12 - ',
 '07/05/2021, 20:14 - ',
 '07/05/2021, 20:14 - ',
 '07/05/2021, 20:26 - ',
 '07/05/2021, 22:24 - ',
 '09/05/2021, 10:41 - ',
 '10/05/2021, 09:15 - ',
 '11/05/2021, 12:49 - ',
 '11/05/2021, 12:49 - ',
 '11/05/2021, 12:53 - ',
 '12/05/2021, 17:21 - ',
 '12/05/2021, 17:41 - ',
 '12/05/2021, 18:09 - ',
 '12/05/2021, 18:11 - ',
 '13/05/2021, 11:47 - ',
 '13/05/2021, 11:48 - ',
 '13/05/2021, 11:52 - ',
 '13/05/2021, 12:07 - ',
 '13/05/2021, 12:10 - ',
 '13/05/2021, 12:15 - ',
 '14/05/2021, 13:07 - ',
 '14/05/2021, 19:56 - ',
 '14/05/2021, 20:04 - ',
 '14/05/2021, 20:16 - ',
 '14/05/2021, 20:16 - ',
 '14/05/2021, 20:22 - ',
 '15/05/2021, 09:15 - ',
 '15/05/2021, 09:54 - ',
 '15/05/2021, 09:56 - ',
 '15/05/2021, 10:57 - ',
 '15/05/2021, 14:31 - ',
 '15/05/2021, 14:35 - ',
 '15/05/2021, 19:42 - ',
 '15/05/2021, 20:00 - ',
 '15/05/2021, 22:32 - ',
 '15/05/2021, 22:33 - ',
 '16/05/2021, 09:19 - ',
 '16/05/2021, 09:19 - ',
 '16/05/2021, 22:30 - ',
 '17/05/2021, 17:53 - ',
 '18/05/2021, 10:52 - ',
 '18/05/2021, 10:54 - ',
 '18/05/2021, 10:58 - ',
 '18/05/2021, 11:27 - ',
 '18/05/2021, 11:27 - ',
 '18/05/2021, 11:29 - ',
 '18/05/2021, 11:29 - ',
 '18/05/2021, 12:06 - ',
 '19/05/2021, 12:25 - ',
 '19/05/2021, 12:31 - ',
 '19/05/2021, 12:39 - ',
 '19/05/2021, 12:40 - ',
 '19/05/2021, 12:42 - ',
 '19/05/2021, 12:42 - ',
 '19/05/2021, 12:43 - ',
 '19/05/2021, 13:16 - ',
 '19/05/2021, 13:16 - ',
 '19/05/2021, 13:16 - ',
 '19/05/2021, 13:18 - ',
 '19/05/2021, 13:18 - ',
 '19/05/2021, 13:18 - ',
 '19/05/2021, 13:24 - ',
 '19/05/2021, 13:24 - ',
 '19/05/2021, 13:24 - ',
 '19/05/2021, 13:26 - ',
 '19/05/2021, 13:26 - ',
 '19/05/2021, 13:26 - ',
 '19/05/2021, 13:31 - ',
 '19/05/2021, 13:31 - ',
 '19/05/2021, 13:31 - ',
 '19/05/2021, 13:32 - ',
 '19/05/2021, 13:35 - ',
 '19/05/2021, 13:35 - ',
 '19/05/2021, 13:43 - ',
 '19/05/2021, 13:43 - ',
 '19/05/2021, 20:31 - ',

In [6]:
df = pd.DataFrame({'user_message': messages, 'message_date': dates})
# convert message_date type
df['message_date'] = pd.to_datetime(df['message_date'], format='%d/%m/%Y, %H:%M - ')
df.rename(columns={ 'message_date': 'date'}, inplace=True)
df.head()

                                        user_message                date
0  Messages and calls are end-to-end encrypted. N... 2020-09-21 21:35:00
1      Harsh created group "Karn's ka jalwa 😎😎😎"\n 2019-05-06 21:22:00
2                                  Harsh added you\n 2020-09-21 20:39:00
3               Bhartendu Karn😊😊: Thanku  manu🙏🏻\n 2020-09-21 21:41:00
4                                Harsh: Hiiii papa\n 2020-09-21 21:41:00

In [7]:
df.shape

(8487, 2)

In [8]:
# splitting username and msg
users = []
messages = []
for message in df['user_message']:
    entry = re.split('([\w\W]+?):\s', message)
    if entry[1:]:  # user name
        users.append(entry[1])
        messages.append(" ".join(entry[2:]))
    else:
        users.append('group_notification')
        messages.append(entry[0])

df['user'] = users
df['message'] = messages
df.drop(columns=['user_message'], inplace=True)
df.head()

,date,user,message
0,2020-09-21 21:35:00,group_notification,Messages and calls are end-to-end encrypted. N...
1,2019-05-06 21:22:00,group_notification,"Harsh created group ""Karn's ka jalwa 😎😎😎""\n"
2,2020-09-21 20:39:00,group_notification,Harsh added you\n
3,2020-09-21 21:41:00,Bhartendu Karn😊😊,Thanku manu🙏🏻\n
4,2020-09-21 21:41:00,Harsh,Hiiii papa\n

In [9]:
df['Year'] = df['date'].dt.year
df.head()

,date,user,message,Year
0,2020-09-21 21:35:00,group_notification,Messages and calls are end-to-end encrypted. N...,2020
1,2019-05-06 21:22:00,group_notification,"Harsh created group ""Karn's ka jalwa 😎😎😎""\n",2019
2,2020-09-21 20:39:00,group_notification,Harsh added you\n,2020
3,2020-09-21 21:41:00,Bhartendu Karn😊😊,Thanku manu🙏🏻\n,2020
4,2020-09-21 21:41:00,Harsh,Hiiii papa\n,2020

In [10]:
df['Month'] = df['date'].dt.month_name()
df.head()

,date,user,message,Year,Month
0,2020-09-21 21:35:00,group_notification,Messages and calls are end-to-end encrypted. N...,2020,September
1,2019-05-06 21:22:00,group_notification,"Harsh created group ""Karn's ka jalwa 😎😎😎""\n",2019,May
2,2020-09-21 20:39:00,group_notification,Harsh added you\n,2020,September
3,2020-09-21 21:41:00,Bhartendu Karn😊😊,Thanku manu🙏🏻\n,2020,September
4,2020-09-21 21:41:00,Harsh,Hiiii papa\n,2020,September

In [11]:
df['day'] = df['date'].dt.day
df.head()

,date,user,message,Year,Month,day
0,2020-09-21 21:35:00,group_notification,Messages and calls are end-to-end encrypted. N...,2020,September,21
1,2019-05-06 21:22:00,group_notification,"Harsh created group ""Karn's ka jalwa 😎😎😎""\n",2019,May,6
2,2020-09-21 20:39:00,group_notification,Harsh added you\n,2020,September,21
3,2020-09-21 21:41:00,Bhartendu Karn😊😊,Thanku manu🙏🏻\n,2020,September,21
4,2020-09-21 21:41:00,Harsh,Hiiii papa\n,2020,September,21

In [12]:
df['hour'] = df['date'].dt.hour
df.head()
df['minute'] = df['date'].dt.minute
df.head()

,date,user,message,Year,Month,day,hour,minute
0,2020-09-21 21:35:00,group_notification,Messages and calls are end-to-end encrypted. N...,2020,September,21,21,35
1,2019-05-06 21:22:00,group_notification,"Harsh created group ""Karn's ka jalwa 😎😎😎""\n",2019,May,6,21,22
2,2020-09-21 20:39:00,group_notification,Harsh added you\n,2020,September,21,20,39
3,2020-09-21 21:41:00,Bhartendu Karn😊😊,Thanku manu🙏🏻\n,2020,September,21,21,41
4,2020-09-21 21:41:00,Harsh,Hiiii papa\n,2020,September,21,21,41

In [13]:
!pip install urlextract

Requirement already satisfied: urlextract in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (1.8.0)
Requirement already satisfied: filelock in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from urlextract) (3.10.0)
Requirement already satisfied: idna in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from urlextract) (2.10)
Requirement already satisfied: uritools in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from urlextract) (4.0.1)
Requirement already satisfied: platformdirs in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from urlextract) (3.1.1)

[notice] A new release of pip available: 22.2.2 -> 23.0.1
[notice] To update, run: pip install --upgrade pip

In [14]:
# from urlextract import URLExtract

# extract = URLExtract()
# links = []
# for message in df['message']:
#     links.extend(extract.find_urls(message))
# len(links)

In [15]:
temp=df[df['user']!="group_notification"]

In [16]:
temp=temp[temp['message']!='<Media omitted>\n']
temp

,date,user,message,Year,Month,day,hour,minute
3,2020-09-21 21:41:00,Bhartendu Karn😊😊,Thanku manu🙏🏻\n,2020,September,21,21,41
4,2020-09-21 21:41:00,Harsh,Hiiii papa\n,2020,September,21,21,41
5,2020-09-21 21:41:00,Harsh,😍😍😍\n,2020,September,21,21,41
6,2020-09-21 21:41:00,Sakshi,Hiii\n,2020,September,21,21,41
7,2020-09-21 21:42:00,Margi,Hiii papa\n,2020,September,21,21,42
...,...,...,...,...,...,...,...,...
8482,2023-04-14 14:24:00,Mummi,kya kar rahi Re pagal hai na\n,2023,April,14,14,24
8483,2023-04-14 14:24:00,Harsh,🤣\n,2023,April,14,14,24
8484,2023-04-14 14:25:00,Sakshi,🫤\n,2023,April,14,14,25
8485,2023-04-14 14:30:00,Sakshi,🌝\n,2023,April,14,14,30
8486,2023-04-14 14:30:00,Sakshi,🍨\n,2023,April,14,14,30

In [17]:
from collections import Counter
words = []


f = open('stop_hinglish.txt','r')
stop_words = f.read()

for message in temp['message']:
    for word in message.lower().split():
        if word not in stop_words:
            words.append(word)

most_common_df = pd.DataFrame(Counter(words).most_common(20))
most_common_df

          0    1
0         😂  253
1         🙄  163
2      papa  106
3         🥲   95
4         🤣   83
5      manu   77
6     sakku   70
7   message   69
8     mummi   67
9     mummy   53
10        🙂   51
11     call   50
12       😂😂   49
13  deleted   49
14    phone   42
15    class   40
16     dena   40
17      chl   38
18      bus   35
19     baat   35

In [18]:
df['Month_num'] = df['date'].dt.month
df.head()

,date,user,message,Year,Month,day,hour,minute,Month_num
0,2020-09-21 21:35:00,group_notification,Messages and calls are end-to-end encrypted. N...,2020,September,21,21,35,9
1,2019-05-06 21:22:00,group_notification,"Harsh created group ""Karn's ka jalwa 😎😎😎""\n",2019,May,6,21,22,5
2,2020-09-21 20:39:00,group_notification,Harsh added you\n,2020,September,21,20,39,9
3,2020-09-21 21:41:00,Bhartendu Karn😊😊,Thanku manu🙏🏻\n,2020,September,21,21,41,9
4,2020-09-21 21:41:00,Harsh,Hiiii papa\n,2020,September,21,21,41,9

In [19]:
timeline=df.groupby(['Year','Month','Month_num']).count()['message'].reset_index()

In [20]:
df

,date,user,message,Year,Month,day,hour,minute,Month_num
0,2020-09-21 21:35:00,group_notification,Messages and calls are end-to-end encrypted. N...,2020,September,21,21,35,9
1,2019-05-06 21:22:00,group_notification,"Harsh created group ""Karn's ka jalwa 😎😎😎""\n",2019,May,6,21,22,5
2,2020-09-21 20:39:00,group_notification,Harsh added you\n,2020,September,21,20,39,9
3,2020-09-21 21:41:00,Bhartendu Karn😊😊,Thanku manu🙏🏻\n,2020,September,21,21,41,9
4,2020-09-21 21:41:00,Harsh,Hiiii papa\n,2020,September,21,21,41,9
...,...,...,...,...,...,...,...,...,...
8482,2023-04-14 14:24:00,Mummi,kya kar rahi Re pagal hai na\n,2023,April,14,14,24,4
8483,2023-04-14 14:24:00,Harsh,🤣\n,2023,April,14,14,24,4
8484,2023-04-14 14:25:00,Sakshi,🫤\n,2023,April,14,14,25,4
8485,2023-04-14 14:30:00,Sakshi,🌝\n,2023,April,14,14,30,4
8486,2023-04-14 14:30:00,Sakshi,🍨\n,2023,April,14,14,30,4